services:
  python-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dify-rag-dev
    volumes: 
      - .:/workspace

    # Run the container in an interactive mode
    tty: true
    stdin_open: true

    env_file:
      - .env

    depends_on:
      - db

    working_dir: /workspace

  db:
    image: postgres:15
    container_name: dify-rag-dev-db
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"