services:
  python-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: dify-rag-dev
    ports:
      - "8088:8000"
    volumes: 
      - .:/workspace
    # Run the container in an interactive mode
    # tty: true
    # stdin_open: true
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    working_dir: /workspace
    networks:
      - chatbot-network

  db:
    image: pgvector/pgvector:pg15
    container_name: dify-rag-dev-db
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c "maintenance_work_mem=2GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - chatbot-network

# Persistent data
volumes:
  postgres-data:

# Connect to Dify
networks:
  chatbot-network:
    external: true